# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: INTELLIGENT SYSTEMS ENGINEERING COLLOQUIUM SERIES
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Webjeda Cards is a Bootstrap based jekyll theme for portfolio, photography or any kind of blog.
organization: The School of Informatics and Computing (SoIC) at Indiana University
  
  
baseurl: "https://iu-ise.github.io/ISE-Colloquium-Series/" # the subpath of your site, e.g. /blog
url: "http://webjeda.com" # the base hostname & protocol for your site

#sidebar
default-image: webjeda-logo-big.jpg # If there is no featured image in a post then this image will be showed. Also on all pages this image will be showed. Use a 500x250 image.

#footer
built-by: webjeda
copyright:
   name: webjeda
   link: 'http://blog.webjeda.com'

# Build settings
markdown: kramdown
permalink: /:title/
paginate: 6
paginate_path: /page:num/

# Tracker
analytics: UA-83979019-1

#social
github: https://iu-ise.github.io/ISE-Colloquium-Series/

# Sass style
sass:
  style: compressed

# Ruby Gems
gems: [jekyll-paginate, jekyll-seo-tag]

